##### 20 - Matrix Identidade

----- *modo 1* : modo mais lógico

In [ ]:
def imprime_matriz(matriz):
    for row in matriz:
        print(row)

In [ ]:
def ident_matrix(n):

    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        matrix.append(row)
    return matrix

matriz = ident_matrix(4)

imprime_matriz(matriz)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


----- *modo 2* : modo mais lógico e pythonic

In [ ]:
def ident_matrix(n):
    
    matrix = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        matrix[i][i] = 1

    return matrix

matriz = ident_matrix(5)

imprime_matriz(matriz)

[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


----- *modo 3* : usando biblioteca numpy

In [ ]:
import numpy as np

matriz = np.identity(4)
imprime_matriz(matriz)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]
