#### **GPT_Tutor**

#### <font color=orange>***Desafios básicos***</font>

##### Imprima "Hello, World!" na tela.

In [4]:
print("Hello, World!")

Hello, World!


##### Some dois números fornecidos pelo usuário

In [5]:
input_1 = int(input())
input_2 = int(input())

print(input_1 + input_2)

13


##### Verifique se um número é par ou ímpar.

In [6]:
num_odd_or_even = 17

if num_odd_or_even % 2 == 0:
    print(f"The number {num_odd_or_even} is even")
else:
    print(f"The number {num_odd_or_even} is odd")

The number 17 is odd


##### Encontre o maior de três números fornecidos pelo usuário.

In [7]:
gt_1 = input()
gt_2 = input()
gt_3 = input()

a = max(gt_1, gt_2, gt_3)

print(f"O maior numero dado como input foi {a}")

O maior numero dado como input foi 9


##### Inverta uma string fornecida pelo usuário

In [8]:
import time

In [9]:
list_rev = [1,2,4,5,67,8,9]

start = time.time()
for l in list_rev[-1::-1]:
    print(l)
end = time.time()

print(f"Tempo gasto: {end-start}")
print(end-start)


print("==============")

start = time.time()
list_rev = reversed(list_rev)
for l in list_rev:
    print(l)
end = time.time()

print(f"Tempo gasto: {end-start}")
print(end-start)


9
8
67
5
4
2
1
Tempo gasto: 0.0003380775451660156
0.0003380775451660156
9
8
67
5
4
2
1
Tempo gasto: 0.00010991096496582031
0.00010991096496582031


In [10]:
string_rev = "Ao verme que primeiro roeu"
new_s = ""

start = time.time()
for l in string_rev[-1::-1]:
    new_s += l
end = time.time()

print(new_s)
print(f"Tempo gasto: {end-start}")


print("==============")

start = time.time()
string_rev = reversed(string_rev)
new_s = ""
for l in string_rev:
    new_s += l
end = time.time()

print(new_s)
print(f"Tempo gasto: {end-start}")


ueor oriemirp euq emrev oA
Tempo gasto: 9.942054748535156e-05
ueor oriemirp euq emrev oA
Tempo gasto: 7.2479248046875e-05


##### Verifique se uma string é um palíndromo

In [11]:
def rev_str(palavra: str) -> str:
    string_rev = reversed(palavra)
    new_s = ""
    for l in string_rev:
        new_s += l
    return new_s

In [12]:
def acha_palindromo(palavra: str) -> str:


    palavra = palavra.lower().strip()

    if len(palavra) % 2 == 0:
        return False

    i = 0
    j = -1

    for _ in palavra:
        if palavra[i] != palavra[j]:
            return False
        i += 1
        j -= 1

    return True

start = time.time()
print(acha_palindromo("    RotaTor     "))
print(acha_palindromo("EU"))
print(acha_palindromo("MoM"))
end = time.time()
print(end-start)

True
False
True
0.00016736984252929688


##### Conte o número de vogais em uma string.

In [13]:

def conta_vogais(palavra: str) -> str:
    
    vogais = ["a", "e", "i", "o", "u"]

    palavra = palavra.strip().lower()

    qtd_vogais = 0
    for l in palavra:
        if l in vogais:
            qtd_vogais += 1
        
    return qtd_vogais

palavra = "Meia"
print(f"{conta_vogais(palavra)} é/são a quantidade de vogais na palavra '{palavra}'")

3 é/são a quantidade de vogais na palavra 'Meia'


##### Imprima os números de 1 a 10 usando um loop.

In [14]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


##### Crie uma lista com os primeiros 10 números quadrados.

In [15]:
dez_primeiros_quadrados = [ (x*x) for x in range(1,11)]
print(dez_primeiros_quadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


##### Concatene duas listas.

In [16]:
list_1_con = [1, 3, "Cinco"]
list_2_con = ["Machado", "Graça", "Austen"]

list_1_con.extend(list_2_con)

print(list_1_con)

[1, 3, 'Cinco', 'Machado', 'Graça', 'Austen']


#### <font color=orange>***Desafios intermediários***</font>

##### Remova duplicatas de uma lista.

In [17]:
list_dup = [1, 2, 3, 3, 3, "oi", "oi"]

sem_dup = list(dict.fromkeys(list_dup))

print(sem_dup)

[1, 2, 3, 'oi']


##### Encontre o valor máximo e mínimo em uma lista.

In [18]:
def minmax(lista: str) -> str:
    min_l = min(lista)
    max_l = max(lista)
    
    return min_l, max_l
    
lista = [1, 9, 13, -1, 77, 1347]

print(minmax(lista))

(-1, 1347)


##### Inverta uma lista sem usar o método reverse().

In [19]:
def list_rev(lista: list) -> list:
    new_l = []
    for i in lista[-1::-1]:
        new_l.append(i)
    return new_l

ll = [1, 9, 14,17,58,65]
print(list_rev(ll))

[65, 58, 17, 14, 9, 1]


##### Ordene uma lista de números.

In [20]:
def ord_list(lista: list) -> list:
    ordered_list = sorted(lista)
    return ordered_list


unord_list = [4, 1, -5, 10, 7, 29, 91, 200, 110, 31, 45, 78]
print(ord_list(unord_list))


[-5, 1, 4, 7, 10, 29, 31, 45, 78, 91, 110, 200]


##### Conte a frequência de cada palavra em uma string.

In [21]:
str_poema = """No meio do caminho tinha uma pedra
tinha uma pedra no meio do caminho
tinha uma pedra
no meio do caminho tinha uma pedra.

Nunca me esquecerei desse acontecimento
na vida de minhas retinas tão fatigadas.
Nunca me esquecerei que no meio do caminho
tinha uma pedra
tinha uma pedra no meio do caminho
no meio do caminho tinha uma pedra."""

In [22]:
from operator import itemgetter


def count_words(texto: str) -> dict:

    l_texto = texto.lower().split()
    dict_words = {}

    for word in l_texto:
        if word in list(dict_words.keys()):
            dict_words[word] = dict_words[word] +1
        else:
            dict_words[word] = 1

    dict_words = sorted(dict_words.items(), key=itemgetter(1), reverse=True)
    
    return dict_words

dict_w = count_words(str_poema)

print(dict_w)




[('tinha', 7), ('uma', 7), ('no', 6), ('meio', 6), ('do', 6), ('caminho', 6), ('pedra', 5), ('pedra.', 2), ('nunca', 2), ('me', 2), ('esquecerei', 2), ('desse', 1), ('acontecimento', 1), ('na', 1), ('vida', 1), ('de', 1), ('minhas', 1), ('retinas', 1), ('tão', 1), ('fatigadas.', 1), ('que', 1)]


In [23]:
import pandas as pd

In [24]:
df = pd.DataFrame(dict_w, columns=['palavra', 'quantidade']).set_index('palavra')
df

quantidade
palavra                  
tinha                   7
uma                     7
no                      6
meio                    6
do                      6
caminho                 6
pedra                   5
pedra.                  2
nunca                   2
me                      2
esquecerei              2
desse                   1
acontecimento           1
na                      1
vida                    1
de                      1
minhas                  1
retinas                 1
tão                     1
fatigadas.              1
que                     1

##### Encontre o índice de um item em uma lista.

In [25]:
def find_index(lista: list, elemento) -> int:

    return lista.index(elemento)

lista_elementos = [1,2,3,9,"dez"]

print(find_index(lista_elementos, 3))
print(find_index(lista_elementos, "dez"))

2
4


##### Implemente uma função para calcular o fatorial de um número.

In [26]:
def fact(n:int) -> int:
    if n < 1:
        return 1
    else:
        return n * fact(n-1)

for i in range(1, 11):
    print(fact(i))

1
2
6
24
120
720
5040
40320
362880
3628800


##### Gere uma lista de números primos até um valor fornecido pelo usuário.

In [27]:
def verifica_primo(n:int) -> bool:

    if n < 2:
        return False
    if n == 2 or n == 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    
    #====== crivo de eratóstenes =======
    i = 5
    while i * i <= n:

        if n % i == 0 or n % (i+2) == 0:
            return False
        
        i += 6
    #===================================

    return True

def primos_abaixo(n:int) -> list:

    todos_os_primos = []

    for i in range (2,n+1):
        if verifica_primo(i):
            todos_os_primos.append(i)
    
    return todos_os_primos

retorno = primos_abaixo(75)
print(retorno)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73]


##### Explicação Crivo de Eratostenes

Essa parte do código faz referência a uma otimização muito comum na verificação de números primos, usando o fato de que **se um número `n` não tem divisores menores ou iguais à sua raiz quadrada, ele não terá divisores maiores que isso**.

Vamos explicar por que isso funciona.


<font color=green>**Divisores vêm em pares**</font>

Todo número composto (não primo) pode ser escrito como o produto de dois números. Por exemplo:

- 36 = 6 × 6
- 18 = 2 × 9
- 100 = 10 × 10

Em cada caso, os divisores de `n` vêm em pares:

- Para 36: os divisores pares são (2, 18), (3, 12), (6, 6), etc.
- Para 100: os divisores pares são (2, 50), (4, 25), (5, 20), (10, 10), etc.

Note que à medida que os divisores aumentam de um lado do par, os divisores correspondentes diminuem do outro lado.

<font color=green>**Importância da raiz quadrada**</font>

Agora, observe que no caso de `n = 36`, o divisor mais próximo do meio é 6 (raiz quadrada de 36). Similarmente, para 100, a raiz quadrada é 10. O que isso significa é que, **se `n` tiver algum divisor maior que sua raiz quadrada**, esse divisor terá que ser combinado com um divisor menor que a raiz quadrada, formando um par. Portanto, se não encontrarmos divisores menores ou iguais à raiz quadrada de `n`, podemos concluir que `n` não tem divisores maiores também.

Por exemplo:

- Se `n = 36` e você testar divisores até a raiz quadrada de 36 (ou seja, até 6), você terá testado todos os possíveis pares de divisores. Se não encontrar um divisor até 6, não há necessidade de verificar valores maiores, pois eles teriam um par divisor menor que 6 (e você já verificou isso).
- Se você testar 7, 8, 9, etc., para `n = 36`, qualquer divisor que encontrar teria que formar um par divisor que é menor que 6, e já sabemos que não há tal divisor.

<font color=green>**Por que `while i * i <= n` ?**</font>

Essa linha é usada para garantir que o loop só teste até a raiz quadrada de `n`. Como a raiz quadrada de `n` é `sqrt(n)`, verificamos se `i * i <= n` ao invés de calcular a raiz quadrada explicitamente para evitar cálculos extras.

<font color=green>**Exemplo prático:**</font>

Vamos dizer que estamos verificando se 37 é primo.

- A raiz quadrada de 37 é aproximadamente 6,08.
- No loop, começamos a testar divisores a partir de 2 e verificamos até 6.
- Se não encontrarmos nenhum divisor até 6, podemos concluir que 37 é primo, porque se 37 tivesse um divisor maior que 6, ele teria um par divisor menor que 6, que já teria sido encontrado.

Essa técnica permite que você reduza drasticamente o número de verificações necessárias para determinar se um número é primo, especialmente quando `n` é grande.

##### Matrix Identidade

----- *modo 1* : modo mais lógico

In [28]:
def imprime_matriz(matriz):
    for row in matriz:
        print(row)

In [29]:
def ident_matrix(n):

    matrix = []
    for i in range(n):
        row = []
        for j in range(n):
            if i == j:
                row.append(1)
            else:
                row.append(0)
        matrix.append(row)
    return matrix

matriz = ident_matrix(4)

imprime_matriz(matriz)


[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]


----- *modo 2* : modo mais lógico e pythonic

In [30]:
def ident_matrix(n):
    
    matrix = [[0 for _ in range(n)] for _ in range(n)]

    for i in range(n):
        matrix[i][i] = 1

    return matrix

matriz = ident_matrix(5)

imprime_matriz(matriz)

[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]


----- *modo 3* : usando biblioteca numpy

In [31]:
import numpy as np

matriz = np.identity(4)
imprime_matriz(matriz)

[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]


#### <font color=orange>***Desafios técnicos***</font>

##### Implemente um algoritmo de busca binária.

In [32]:
import math

In [33]:
def order_list(lista):
    ord_l = sorted(lista)
    return ord_l

def busca_binaria(lista, alvo):

    lista = order_list(lista)

    inicio = 0
    fim = len(lista)-1

    while inicio <= fim:

        meio = math.floor((inicio+fim)/2)

        if lista[meio] == alvo:
            return alvo, meio
        elif lista[meio] < alvo:
            inicio = meio + 1
        elif lista[meio] > alvo:
            fim = meio - 1
    
    return None

num_lista_bin = [34, 5, 7, 1, 120, 45, -7, 9, 3, 213, 11, 47]
alvo = busca_binaria(num_lista_bin, 47)
print(alvo)

(47, 9)


##### -